[package]
name = "escribo"
version = "0.1.0"
edition = "2021"
authors = ["Samyak Gangwal <sam.gangwal97@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
termion = "1.5.6"